on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build: 
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Nodejs Setup
        uses: actions/setup-node@v3
        with: 
          node-version: 16

      - name: Install yarn latest version
        run: npm install -g yarn

      - name: Install typescript globally
        run: yarn add typescript -G

      - name: Install Dependencies
        run: yarn

      - name: Build Typescript
        run: yarn build

      - name: Run Tests
        run: yarn test
